In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import cv2
import os
import numpy as np
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing import image
from tensorflow.keras.optimizers import RMSprop

In [2]:
img=cv2.imread(r"D:\image classification\seg_pred\seg_pred\5.jpg")
print(img)
img.shape

[[[171 137 138]
  [171 137 138]
  [171 137 138]
  ...
  [179 146 137]
  [181 145 137]
  [184 148 140]]

 [[171 137 138]
  [172 138 139]
  [172 138 139]
  ...
  [177 143 137]
  [180 144 138]
  [183 147 141]]

 [[170 138 139]
  [170 138 139]
  [170 137 141]
  ...
  [186 151 147]
  [182 147 143]
  [178 143 139]]

 ...

 [[ 23  19  30]
  [ 24  20  31]
  [ 22  22  34]
  ...
  [ 48  43  42]
  [ 43  38  37]
  [ 40  35  34]]

 [[ 23  25  25]
  [ 23  27  28]
  [ 23  28  31]
  ...
  [ 40  35  32]
  [ 39  34  31]
  [ 39  34  31]]

 [[ 20  26  21]
  [ 21  28  25]
  [ 22  28  27]
  ...
  [ 46  41  38]
  [ 49  44  41]
  [ 51  46  43]]]


(150, 150, 3)

In [3]:
train=ImageDataGenerator(1/255)
test=ImageDataGenerator(1/255)



In [17]:
train_dataset=train.flow_from_directory(r"D:\image classification\seg_train\seg_train", target_size=(150,150), batch_size=32)

Found 14034 images belonging to 6 classes.


In [18]:
validation_dataset=test.flow_from_directory(r"D:\image classification\seg_test\seg_test", target_size=(150,150), batch_size=32)

Found 3000 images belonging to 6 classes.


In [6]:
train_dataset.class_indices

{'buildings': 0,
 'forest': 1,
 'glacier': 2,
 'mountain': 3,
 'sea': 4,
 'street': 5}

In [20]:
model=tf.keras.Sequential([
    tf.keras.layers.Conv2D(32,(3,3),activation='relu', input_shape=(150,150,3)),
    tf.keras.layers.MaxPool2D(2,2),
    tf.keras.layers.Conv2D(64,(3,3), activation='relu'),
    tf.keras.layers.MaxPool2D(2,2),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(6)
])

In [25]:
model.compile(optimizer=RMSprop(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [26]:
history=model.fit(train_dataset, epochs=10, validation_data=validation_dataset)

Epoch 1/10
439/439 [==============================] - 531s 1s/step - loss: 10.4719 - accuracy: 0.1785 - val_loss: 10.6057 - val_accuracy: 0.1750
Epoch 2/10
439/439 [==============================] - 496s 1s/step - loss: 10.4973 - accuracy: 0.1790 - val_loss: 10.6057 - val_accuracy: 0.1750
Epoch 3/10
439/439 [==============================] - 510s 1s/step - loss: 10.4973 - accuracy: 0.1790 - val_loss: 10.6057 - val_accuracy: 0.1750
Epoch 4/10
439/439 [==============================] - 512s 1s/step - loss: 10.4973 - accuracy: 0.1790 - val_loss: 10.6057 - val_accuracy: 0.1750
Epoch 5/10
439/439 [==============================] - 522s 1s/step - loss: 10.4973 - accuracy: 0.1790 - val_loss: 10.6057 - val_accuracy: 0.1750
Epoch 6/10
439/439 [==============================] - 698s 2s/step - loss: 10.4973 - accuracy: 0.1790 - val_loss: 10.6057 - val_accuracy: 0.1750
Epoch 7/10
439/439 [==============================] - 7939s 18s/step - loss: 10.4973 - accuracy: 0.1790 - val_loss: 10.6057 - val_